<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="Main.aspx.cs" Inherits="OnlineHealthcareManagementSystem.Main" %>

<asp:Content ID="Master" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="ContentAdmin" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
<%--    <header>
          <h1 align="Center">
              <b>
                  <i>Online Healthcare Management System
                  </i>
              </b>
          </h1>
      </header>--%>
      <asp:GridView ID="PatientGridView" runat="server" AutoGenerateColumns="false" DataKeyNames="UserID" AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True" OnSelectedIndexChanged="CustomerGridView_SelectedIndexChanged" onrowcancelingedit="PatientGridView_RowCancelingEdit" 
          onrowdeleting="PatientRowDeleting" onrowediting="PatientGridView_RowEditing" onrowupdating="PatientRowUpdating" ShowFooter="true">
        <Columns>
<%--              <asp:BoundField DataField="patientID" HeaderText="PatientId" ReadOnly="true"/>--%>
            <asp:TemplateField HeaderText="Patient ID">
                <ItemTemplate>
                    <asp:Label ID="labelid" runat="server" Text='<%# Bind("Userid") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:LinkButton ID ="InsertButton" runat="server" Text="Insert"></asp:LinkButton>
                </FooterTemplate>
                </asp:TemplateField>
              <asp:TemplateField HeaderText="Patient Name">
                <EditItemTemplate>
                    <asp:TextBox ID="txtName" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelName" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Gender">
                <EditItemTemplate>
                    <asp:TextBox ID="txtSex" runat="server" Text='<%# Bind("sex") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelSex" runat="server" Text='<%# Bind("sex") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

                        <asp:TemplateField HeaderText="Date of Birth">
                <EditItemTemplate>
                    <asp:TextBox ID="txtDob" runat="server" Text='<%# Bind("dob") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelDob" runat="server" Text='<%# Bind("dob") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="bloodgroup">
                <EditItemTemplate>
                    <asp:TextBox ID="txtBloodGroup" runat="server" Text='<%# Bind("bloodGroup") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelBloodGroup" runat="server" Text='<%# Bind("bloodGroup") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>      
            <asp:TemplateField HeaderText="Address">
                <EditItemTemplate>
                    <asp:TextBox ID="txtAddress" runat="server" Text='<%# Bind("Address") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelAddress" runat="server" Text='<%# Bind("Address") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Contact number">
                <EditItemTemplate>
                    <asp:TextBox ID="txtNumber" runat="server" Text='<%# Bind("mobileNumber") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelNumber" runat="server" Text='<%# Bind("mobileNumber") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>  
            <asp:TemplateField HeaderText="Patient mailId">
                <EditItemTemplate>
                    <asp:TextBox ID="txtMail" runat="server" Text='<%# Bind("mailId") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelMail" runat="server" Text='<%# Bind("mailId") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="password">
                <EditItemTemplate>
                    <asp:TextBox ID="txtPassword" runat="server" Text='<%# Bind("password") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelPassword" runat="server" Text='<%# Bind("password") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Confirm password">
                <EditItemTemplate>
                    <asp:TextBox ID="txtConfirmPassword" runat="server" Text='<%# Bind("confirmPassword") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelConfirmPassword" runat="server" Text='<%# Bind("confirmPassword") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
